workflows: support for locally hosted runners

diff --git a/.github/actions/chrome/action.yml b/.github/actions/chrome/action.yml
--- a/.github/actions/chrome/action.yml
+++ b/.github/actions/chrome/action.yml
@@ -18,7 +18,14 @@ runs:
         git clone --single-branch --branch chrome-for-testing https://github.com/cloudengio/citools.git $RUNNER_TEMP/citools
         (cd $RUNNER_TEMP/citools/chrome-for-testing && go install .)
         #go install cloudeng.io/citools/chrome-for-testing@latest
-        chrome-for-testing install --channel=stable --application=chrome --debug
+        chrome-for-testing install --channel=stable --application=chrome --debug --initialize
+
+    - name: resolve chrome user data dir
+      shell: bash
+      run: |
+        echo "chrome path" {{ steps.setup-chrome.outputs.chrome-path }}"
+        echo "chrome data dir" {{ steps.setup-chrome.outputs.chrome-user-data-dir }}"
+
       #if: ${{ runner.os != 'macOS' && runner.environment != 'self-hosted' }}
       #uses: browser-actions/setup-chrome@v2.1.0
       #id: setup-chrome
@@ -26,103 +33,110 @@ runs:
       #  install-dependencies: true
       #  chrome-version: stable
 
-    - name: resolve chrome user data dir
-      id: user-data-dir
-      shell: bash
-      env:
-        USERDATA_DIR: '{"Linux": "$HOME/.config/google-chrome-for-testing", "Windows": "$RUNNER_TEMP\\chrome-user-data", "macOS": "$HOME/Library/Application Support/Google/Chrome for Testing"}'
-      run: |
-        echo "chrome-user-data-dir=${{ fromJSON(env.USERDATA_DIR)[runner.os] }}" >> "$GITHUB_OUTPUT"
+      # C:\Users\<Your_Username>\AppData\Local\Google\Chrome
+      # %LOCALAPPDATA%\Google\Chrome\User Data
 
-    - name: init chrome Linux
-      shell: bash
-      id: init-linux
-      if: ${{ runner.os == 'Linux' }}
-      run: |
-        CHROME_PATH="${{ steps.setup-chrome.outputs.chrome-path }}"
-        USERDATA_DIR="${{ steps.user-data-dir.outputs.chrome-user-data-dir }}"
-        "$CHROME_PATH" --version
-        "$CHROME_PATH" --headless=new --disable-gpu --no-sandbox --remote-debugging-port=9222 --user-data-dir="$USERDATA_DIR" about:blank &
-        CHROME_PID=$!
-        waitforfiles --initial=5s --interval=1s --total=30s "$HOME/.pki/nssdb"
-        if [ $? -ne 0 ]; then
-          kill $CHROME_PID
-            exit 1
-          fi
-        kill $CHROME_PID
+    #  id: user-data-dir
+    #  shell: bash
+    #  env:
 
-        # this should already exist.
-        waitforfiles --interval=0 --total=0 "$USERDATA_DIR/Default"
-        echo "user-data-dir=$USERDATA_DIR" >> "$GITHUB_OUTPUT"
+    #- name: resolve chrome user data dir
+    #  id: user-data-dir
+    #  shell: bash
+    #  env:
+    #    USERDATA_DIR: '{"Linux": "$HOME/.config/google-chrome-for-testing", "Windows": "$RUNNER_TEMP\\chrome-user-data", "macOS": "$HOME/Library/Application Support/Google/Chrome for Testing"}'
+    #  run: |
+    #    echo "chrome-user-data-dir=${{ fromJSON(env.USERDATA_DIR)[runner.os] }}" >> "$GITHUB_OUTPUT"
 
-    - name: init chrome Windows
-      shell: pwsh
-      id: init-windows
-      if: ${{ runner.os == 'Windows' }}
-      run: |
-        $chromePath = "${{ steps.setup-chrome.outputs.chrome-path }}"
-        $userDataDir = "${{ steps.user-data-dir.outputs.chrome-user-data-dir }}"
+    #- name: init chrome Linux
+    #  shell: bash
+    #  id: init-linux
+    #  if: ${{ runner.os == 'Linux' }}
+    #  run: |
+    #    CHROME_PATH="${{ steps.setup-chrome.outputs.chrome-path }}"
+    #    USERDATA_DIR="${{ steps.user-data-dir.outputs.chrome-user-data-dir }}"
+    #    "$CHROME_PATH" --version
+    #    "$CHROME_PATH" --headless=new --disable-gpu --no-sandbox --remote-debugging-port=9222 #--user-data-dir="$USERDATA_DIR" about:blank &
+    #    CHROME_PID=$!
+    #    waitforfiles --initial=5s --interval=1s --total=30s "$HOME/.pki/nssdb"
+    #    if [ $? -ne 0 ]; then
+    #      kill $CHROME_PID
+    #        exit 1
+    #      fi
+    #    kill $CHROME_PID
 
-        & "$chromePath" --version
+    # this should already exist.
+    #   waitforfiles --interval=0 --total=0 "$USERDATA_DIR/Default"
+    #   echo "user-data-dir=$USERDATA_DIR" >> "$GITHUB_OUTPUT"
 
-        # Set sandbox permissions
-        $chromeDir = Split-Path -Parent $chromePath
-        icacls "$chromeDir" /grant 'ALL APPLICATION PACKAGES:(OI)(CI)(RX)' /grant 'ALL RESTRICTED APPLICATION PACKAGES:(OI)(CI)(RX)' /T /C | Out-Null
-        if ($LASTEXITCODE -ne 0) {
-          throw "icacls failed to set sandbox permissions on $chromeDir"
-        }
+    #- name: init chrome Windows
+    #  shell: pwsh
+    #  id: init-windows
+    #  if: ${{ runner.os == 'Windows' }}
+    #  run: |
+    #    $chromePath = "${{ steps.setup-chrome.outputs.chrome-path }}"
+    #    $userDataDir = "${{ steps.user-data-dir.outputs.chrome-user-data-dir }}"
 
-        $profilePath = Join-Path $userDataDir "Default"
+    #    & "$chromePath" --version
 
-        $flags = @(
-          "--headless=new",
-          "--disable-gpu",
-          "--no-sandbox",
-          "--remote-debugging-port=9222",
-          "--user-data-dir=$userDataDir",
-          "about:blank"
-        )
+    # Set sandbox permissions
+    #    $chromeDir = Split-Path -Parent $chromePath
+    #    icacls "$chromeDir" /grant 'ALL APPLICATION PACKAGES:(OI)(CI)(RX)' /grant 'ALL RESTRICTED APPLICATION PACKAGES:(OI)(CI)(RX)' /T /C | Out-Null
+    #    if ($LASTEXITCODE -ne 0) {
+    #      throw "icacls failed to set sandbox permissions on $chromeDir"
+    #    }
 
-        $process = Start-Process -FilePath "$chromePath" -ArgumentList $flags -PassThru
+    #    $profilePath = Join-Path $userDataDir "Default"
 
-        $goBinPath = (go env GOBIN)
-        if (-not $goBinPath) {
-          $goBinPath = (go env GOPATH) + "\bin"
-        }
+    #    $flags = @(
+    #      "--headless=new",
+    #      "--disable-gpu",
+    #      "--no-sandbox",
+    #      "--remote-debugging-port=9222",
+    #      "--user-data-dir=$userDataDir",
+    #      "about:blank"
+    #    )
 
-        & "$goBinPath\waitforfiles.exe" --initial=5s --interval=1s --total=30s $profilePath
-        Stop-Process -Id $process.Id -Force
+    #    $process = Start-Process -FilePath "$chromePath" -ArgumentList $flags -PassThru
 
-    - name: init chrome macOS
-      shell: bash
-      id: init-macos
-      if: ${{ runner.os == 'macOS' }}
-      run: |
-        #CHROME_PATH="/Applications/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing"
-        CHROME_PATH="${{ steps.setup-chrome.outputs.chrome-path }}"
+    #    $goBinPath = (go env GOBIN)
+    #    if (-not $goBinPath) {
+    #      $goBinPath = (go env GOPATH) + "\bin"
+    #    }
 
-        "$CHROME_PATH" --version
+    #    & "$goBinPath\waitforfiles.exe" --initial=5s --interval=1s --total=30s $profilePath
+    #    Stop-Process -Id $process.Id -Force
 
-        USERDATA_DIR="${{ steps.user-data-dir.outputs.chrome-user-data-dir }}"
+    #- name: init chrome macOS
+    #  shell: bash
+    ##  id: init-macos
+    #  if: ${{ runner.os == 'macOS' }}
+    #  run: |
+    #CHROME_PATH="/Applications/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing"
+    #    CHROME_PATH="${{ steps.setup-chrome.outputs.chrome-path }}"
 
-        PROFILE_DIR="$USERDATA_DIR/Default"
+    #    "$CHROME_PATH" --version
 
-        mkdir -p "$PROFILE_DIR"
+    #    USERDATA_DIR="${{ steps.user-data-dir.outputs.chrome-user-data-dir }}"
 
-        "$CHROME_PATH" \
-            --headless=new \
-            --no-sandbox \
-            --disable-gpu \
-            --no-first-run \
-            --no-default-browser-check \
-            --user-data-dir="$USERDATA_DIR" \
-            about:blank &
+    #    PROFILE_DIR="$USERDATA_DIR/Default"
 
-        CHROME_PID=$!
+    #    mkdir -p "$PROFILE_DIR"
 
-        waitforfiles --initial=2s --interval=1s --total=30s "$PROFILE_DIR"
-        if [ $? -ne 0 ]; then
-          kill $CHROME_PID
-          exit 1
-        fi
-        kill $CHROME_PID
+    #    "$CHROME_PATH" \
+    #        --headless=new \
+    #        --no-sandbox \
+    ##        --disable-gpu \
+    #        --no-first-run \
+    #        --no-default-browser-check \
+    #        --user-data-dir="$USERDATA_DIR" \
+    #        about:blank &
+
+    #    CHROME_PID=$!
+
+    #    waitforfiles --initial=2s --interval=1s --total=30s "$PROFILE_DIR"
+    #    if [ $? -ne 0 ]; then
+    #      kill $CHROME_PID
+    #      exit 1
+    #    fi
+    #    kill $CHROME_PID
